import {
  pgTable,
  text,
  varchar,
  timestamp,
  decimal,
  integer,
  boolean,
  serial,
  jsonb,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  passwordHash: text("password_hash").notNull(),
  pin: varchar("pin", { length: 6 }),
  currency: varchar("currency", { length: 10 }).notNull().default("USD"),
  theme: varchar("theme", { length: 10 }).notNull().default("dark"),
  language: varchar("language", { length: 10 }).notNull().default("en"),
  initialBalance: decimal("initial_balance", { precision: 15, scale: 2 }).notNull().default("10000"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const accounts = pgTable("accounts", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  broker: varchar("broker", { length: 100 }),
  initialBalance: decimal("initial_balance", { precision: 15, scale: 2 }).notNull().default("10000"),
  currency: varchar("currency", { length: 10 }).notNull().default("USD"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const trades = pgTable("trades", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  accountId: integer("account_id").references(() => accounts.id, { onDelete: "set null" }),
  pair: varchar("pair", { length: 20 }).notNull(),
  date: timestamp("date").notNull(),
  session: varchar("session", { length: 20 }),
  position: varchar("position", { length: 10 }).notNull(),
  entry: decimal("entry", { precision: 15, scale: 5 }),
  stopLoss: decimal("stop_loss", { precision: 15, scale: 5 }),
  takeProfit: decimal("take_profit", { precision: 15, scale: 5 }),
  riskPercent: decimal("risk_percent", { precision: 5, scale: 2 }),
  reward: decimal("reward", { precision: 15, scale: 2 }),
  rr: decimal("rr", { precision: 5, scale: 2 }),
  lotSize: decimal("lot_size", { precision: 10, scale: 2 }),
  result: varchar("result", { length: 20 }).notNull(),
  profit: decimal("profit", { precision: 15, scale: 2 }).default("0"),
  loss: decimal("loss", { precision: 15, scale: 2 }).default("0"),
  commission: decimal("commission", { precision: 10, scale: 2 }).default("0"),
  notes: text("notes"),
  psychologyNotes: text("psychology_notes"),
  mistakes: text("mistakes"),
  lessonsLearned: text("lessons_learned"),
  checklist: jsonb("checklist"),
  emotionBefore: varchar("emotion_before", { length: 30 }),
  emotionAfter: varchar("emotion_after", { length: 30 }),
  tags: jsonb("tags"),
  strategyName: varchar("strategy_name", { length: 100 }),
  market: varchar("market", { length: 30 }),
  timeframe: varchar("timeframe", { length: 20 }),
  broker: varchar("broker", { length: 100 }),
  screenshotBefore: text("screenshot_before"),
  screenshotAfter: text("screenshot_after"),
  voiceNote: text("voice_note"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const missedTrades = pgTable("missed_trades", {
  id: serial("id").primaryKey(),
  accountId: integer("account_id").references(() => accounts.id, { onDelete: "set null" }),
  pair: varchar("pair", { length: 20 }).notNull(),
  date: timestamp("date").notNull(),
  session: varchar("session", { length: 20 }),
  position: varchar("position", { length: 10 }).notNull(),
  entry: decimal("entry", { precision: 15, scale: 5 }),
  stopLoss: decimal("stop_loss", { precision: 15, scale: 5 }),
  takeProfit: decimal("take_profit", { precision: 15, scale: 5 }),
  rr: decimal("rr", { precision: 5, scale: 2 }),
  potentialProfit: decimal("potential_profit", { precision: 15, scale: 2 }).default("0"),
  strategyName: varchar("strategy_name", { length: 100 }),
  market: varchar("market", { length: 30 }),
  timeframe: varchar("timeframe", { length: 20 }),
  reason: text("reason"),
  category: varchar("category", { length: 50 }),
  screenshotAfter: text("screenshot_after"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const offSessionTrades = pgTable("off_session_trades", {
  id: serial("id").primaryKey(),
  accountId: integer("account_id").references(() => accounts.id, { onDelete: "set null" }),
  pair: varchar("pair", { length: 20 }).notNull(),
  date: timestamp("date").notNull(),
  tradeHour: integer("trade_hour").notNull(),
  tradeMinute: integer("trade_minute").notNull().default(0),
  position: varchar("position", { length: 10 }).notNull(),
  entry: decimal("entry", { precision: 15, scale: 5 }),
  stopLoss: decimal("stop_loss", { precision: 15, scale: 5 }),
  takeProfit: decimal("take_profit", { precision: 15, scale: 5 }),
  rr: decimal("rr", { precision: 5, scale: 2 }),
  lotSize: decimal("lot_size", { precision: 10, scale: 2 }),
  result: varchar("result", { length: 20 }).notNull(),
  profit: decimal("profit", { precision: 15, scale: 2 }).default("0"),
  loss: decimal("loss", { precision: 15, scale: 2 }).default("0"),
  commission: decimal("commission", { precision: 10, scale: 2 }).default("0"),
  strategyName: varchar("strategy_name", { length: 100 }),
  market: varchar("market", { length: 30 }),
  timeframe: varchar("timeframe", { length: 20 }),
  screenshotAfter: text("screenshot_after"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
